//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chorus.Properties {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chorus.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to
		///	 Note: Using Microsoft WORD 2003 or later is not a good way to edit this xml file.
		///	 Instead, use NotePad or WordPad. .
		/// </summary>
		internal static string AdaptItKbDescription {
			get {
				return ResourceManager.GetString("AdaptItKbDescription", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
		///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
		///
		///  &lt;xsl:template match=&quot;/KB&quot;&gt;
		///    &lt;KB docVersion=&quot;{@docVersion}&quot; srcName=&quot;{@srcName}&quot; tgtName=&quot;{@tgtName}&quot; max=&quot;{@max}&quot;&gt;
		///      &lt;xsl:for-each select=&quot;MAP&quot;&gt;
		///        &lt;xsl:sort select=&quot;@mn&quot; order=&quot;ascending&quot;/&gt;
		///        &lt;MAP mn=&quot;{@mn}&quot;&gt;
		///          &lt;xsl:for-each select=&quot;TU&quot;&gt;
		///            &lt;xsl:sort select=&quot;@k&quot; order=&quot;ascending&quot;/&gt;
		///            &lt;TU f=&quot;{@f}&quot; k=&quot;{@k}&quot;&gt;
		///              &lt;xsl:f [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string SortAIKB {
			get {
				return ResourceManager.GetString("SortAIKB", resourceCulture);
			}
		}
	}
}
