//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chorus.Properties {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chorus.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		internal static System.Drawing.Bitmap chorus32x32 {
			get {
				object obj = ResourceManager.GetObject("chorus32x32", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.IO.UnmanagedMemoryStream errorSound {
			get {
				return ResourceManager.GetStream("errorSound", resourceCulture);
			}
		}

		internal static System.IO.UnmanagedMemoryStream finishedSound {
			get {
				return ResourceManager.GetStream("finishedSound", resourceCulture);
			}
		}

		internal static System.Drawing.Bitmap internet29x32 {
			get {
				object obj = ResourceManager.GetObject("internet29x32", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap internet59x64 {
			get {
				object obj = ResourceManager.GetObject("internet59x64", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap networkFolder29x32 {
			get {
				object obj = ResourceManager.GetObject("networkFolder29x32", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap networkFolder58x64 {
			get {
				object obj = ResourceManager.GetObject("networkFolder58x64", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap send_receive_small {
			get {
				object obj = ResourceManager.GetObject("send_receive_small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Usb32x28 {
			get {
				object obj = ResourceManager.GetObject("Usb32x28", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Usb64x64 {
			get {
				object obj = ResourceManager.GetObject("Usb64x64", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap warningImage {
			get {
				object obj = ResourceManager.GetObject("warningImage", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.IO.UnmanagedMemoryStream warningSound {
			get {
				return ResourceManager.GetStream("warningSound", resourceCulture);
			}
		}
	}
}
