//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chorus.Properties {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chorus.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		internal static System.Drawing.Bitmap check12x12 {
			get {
				object obj = ResourceManager.GetObject("check12x12", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap check16x16 {
			get {
				object obj = ResourceManager.GetObject("check16x16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap chorus32x32 {
			get {
				object obj = ResourceManager.GetObject("chorus32x32", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Committer_Person {
			get {
				object obj = ResourceManager.GetObject("Committer Person", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.IO.UnmanagedMemoryStream errorSound {
			get {
				return ResourceManager.GetStream("errorSound", resourceCulture);
			}
		}

		internal static System.Drawing.Bitmap expand {
			get {
				object obj = ResourceManager.GetObject("expand", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Filter {
			get {
				object obj = ResourceManager.GetObject("Filter", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.IO.UnmanagedMemoryStream finishedSound {
			get {
				return ResourceManager.GetStream("finishedSound", resourceCulture);
			}
		}

		internal static System.Drawing.Bitmap internet29x32 {
			get {
				object obj = ResourceManager.GetObject("internet29x32", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap internet59x64 {
			get {
				object obj = ResourceManager.GetObject("internet59x64", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap menuButton {
			get {
				object obj = ResourceManager.GetObject("menuButton", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap networkFolder29x32 {
			get {
				object obj = ResourceManager.GetObject("networkFolder29x32", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap networkFolder58x64 {
			get {
				object obj = ResourceManager.GetObject("networkFolder58x64", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap NewNote16x16 {
			get {
				object obj = ResourceManager.GetObject("NewNote16x16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap search16x16 {
			get {
				object obj = ResourceManager.GetObject("search16x16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap search18x18 {
			get {
				object obj = ResourceManager.GetObject("search18x18", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap send_receive_small {
			get {
				object obj = ResourceManager.GetObject("send_receive_small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap sendReceiveCircle16x16png {
			get {
				object obj = ResourceManager.GetObject("sendReceiveCircle16x16png", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Usb32x28 {
			get {
				object obj = ResourceManager.GetObject("Usb32x28", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Usb64x64 {
			get {
				object obj = ResourceManager.GetObject("Usb64x64", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap warning16x16 {
			get {
				object obj = ResourceManager.GetObject("warning16x16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap warning24x24 {
			get {
				object obj = ResourceManager.GetObject("warning24x24", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap warningImage {
			get {
				object obj = ResourceManager.GetObject("warningImage", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.IO.UnmanagedMemoryStream warningSound {
			get {
				return ResourceManager.GetStream("warningSound", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
		///&lt;!--
		/// |
		/// | XSLT REC Compliant Version of IE5 Default Stylesheet
		/// |
		/// | Original version by Jonathan Marsh (jmarsh@xxxxxxxxxxxxx)
		/// | http://msdn.microsoft.com/xml/samples/defaultss/defaultss.xsl
		/// |
		/// | Conversion to XSLT 1.0 REC Syntax by Steve Muench (smuench@xxxxxxxxxx)
		/// |
		/// | 14-Mar-2008 George Zabanah Modifications made to the XSLT stylesheet
		/// |                            to add a little spacing and change default colour
		/// |                            of na [rest of string was truncated]&quot;;.
		/// </summary>
		internal static string XmlToHtml10Basic {
			get {
				return ResourceManager.GetString("XmlToHtml10Basic", resourceCulture);
			}
		}
	}
}
