//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chorus.UI.Review.RevisionsInRepository {
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class HistoryRowIcons {

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal HistoryRowIcons() {
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chorus.UI.Review.RevisionsInRepository.HistoryRowIcons", typeof(HistoryRowIcons).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		internal static System.Drawing.Bitmap Bloom16x16 {
			get {
				object obj = ResourceManager.GetObject("Bloom16x16", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Conflict {
			get {
				object obj = ResourceManager.GetObject("Conflict", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap FieldWorks {
			get {
				object obj = ResourceManager.GetObject("FieldWorks", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap GenericCheckin {
			get {
				object obj = ResourceManager.GetObject("GenericCheckin", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Merge {
			get {
				object obj = ResourceManager.GetObject("Merge", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Warning {
			get {
				object obj = ResourceManager.GetObject("Warning", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap WeSay {
			get {
				object obj = ResourceManager.GetObject("WeSay", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap WeSayConfiguration {
			get {
				object obj = ResourceManager.GetObject("WeSayConfiguration", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
